name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: codacy-analysis-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli@6a34606
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          max-issues-allowed: 90
      - name: Upload results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
