name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: codacy-analysis-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli@8cff364a8ad8d1bd867f778f02f3594e2330524b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
