name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: codacy-analysis-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli@e43f555fc887f8c0f77f458f2e575699ece77aee
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
