name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: codacy-analysis-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli@21a940b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
